<?php

namespace Phossa\Shared\Error;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 08:38:18.
 */
class ErrorAwareTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ErrorAwareInterface
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include_once __DIR__ . '/ErrorAware.php';
        $this->object = new ErrorAware();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Shared\ErrorAware\ErrorAwareTrait::setError
     * @covers Phossa\Shared\ErrorAware\ErrorAwareTrait::getError
     * @covers Phossa\Shared\ErrorAware\ErrorAwareTrait::getErrorCode
     */
    public function testSetError()
    {
        $this->object->setError('Error1', 'x00');
        $this->assertEquals('Error1', $this->object->getError());
        $this->assertEquals('x00', $this->object->getErrorCode());
        $this->assertFalse($this->object->hasError());

        // test zero
        $this->object->setError('Error2', '000');
        $this->assertEquals('', $this->object->getErrorCode());
        $this->assertTrue($this->object->hasError());
    }
}
