<?php

namespace Phossa\Shared\Message\Formatter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-15 at 03:29:07.
 */
class HtmlFormatterTest
    extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HtmlFormatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HtmlFormatter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Phossa\Shared\Message\Formatter\HtmlFormatter::formatMessage
     * @dataProvider dataProvider
     */
    public function testFormatMessage($template, $arguments, $expect)
    {
        $this->assertEquals(
            $expect, $this->object->formatMessage($template, $arguments)
        );
    }

    /**
     * test dataprovider
     */
    public function dataProvider()
    {
        return array(
            // simple one
            array('Hello %s', ['John'], '<span class="message">Hello <b>John</b></span>'),
            // %s not match
            array('Hello %s', ['John', 'Tom'], '<span class="message">Hello <b>John</b> <b>Tom</b></span>'),
            // %s not match2
            array('Hello %s %s', ['John'], '<span class="message">Hello <b>John</b> <b></b></span>'),
            // non string argument
            array('Hello %s %s', [1.2, false], '<span class="message">Hello <b>1.2</b> <b></b></span>'),
        );
    }

}
