<?php

namespace Phossa\Shared\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 07:22:14.
 */
class RuntimeExceptionTest
    extends \PHPUnit_Framework_TestCase
{

    /**
     * @var RuntimeException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RuntimeException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * test instanceof \RuntimeException
     */
    public function test1()
    {
        $this->assertTrue($this->object instanceof \RuntimeException);
    }

    /**
     * test instanceof Phossa\Shared\Exception\ExceptionInterface
     */
    public function test2()
    {
        $this->assertTrue($this->object instanceof ExceptionInterface);
    }

}
