<?php

namespace Phossa\Shared\Message\Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-15 at 04:45:44.
 */
class LanguageLoaderTest
    extends \PHPUnit_Framework_TestCase
{

    /**
     * @var LanguageLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LanguageLoader('zh_CN');

        // load test classes
        require_once __DIR__ . '/Test.php';
        require_once __DIR__ . '/Test2.php';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Phossa\Shared\Message\Loader\LanguageLoader::setLanguage
     */
    public function testSetLanguage()
    {
        // set language 'zh_CN'
        $lang = 'test';

        $this->object->setLanguage($lang);
        $this->assertEquals($lang, $this->object->getLanguage());
    }

    /**
     * @covers Phossa\Shared\Message\Loader\LanguageLoader::getLanguage
     */
    public function testGetLanguage()
    {
        $this->assertEquals('zh_CN', $this->object->getLanguage());
        return $this->object->getLanguage();
    }

    /**
     * @covers Phossa\Shared\Message\Loader\LanguageLoader::loadMessages
     * @depends testGetLanguage
     */
    public function testLoadMessages($lang)
    {
        // nonexit class
        $res1 = $this->object->loadMessages('NonExistClass');
        $this->assertEquals([], $res1);

        // not find language file
        $res2 = $this->object->loadMessages(Test2::getClass());
        $this->assertEquals([], $res2);

        $res3 = $this->object->loadMessages(Test::getClass());
        $this->assertEquals(['lang' => $lang], $res3);
    }

}
